Main page improvement
WoodMechanics/wood-form pull request #8
Opened 2024-01-24 07:34 UTC by Winechicken

2024-02-11 13:15 UTC, SavaCool122 requested changes

2024-02-11 13:15 UTC, SavaCool122 commented on src/components/homePage/section/RecentForm.vue
> +// let changeImage = document.querySelector('#changeImage')
Looks like unnecessary comments here

2024-02-11 13:15 UTC, SavaCool122 commented on src/components/homePage/section/RecentForm.vue
> +						id="changeImage"
Looks like unnecessary id here

2024-02-11 13:15 UTC, SavaCool122 commented on src/components/homePage/section/RecentForm.vue
> +						<img src="../../../assets/icons/list.svg" alt="" />
Les't do better for our developer experience and implement new rule #9

2024-02-14 21:34 UTC, Winechicken commented on src/components/homePage/header/MainPageHeader.vue
> +				<button type="submit"><img src="../../../assets/icons/icons8-search.svg" alt="" /></button>
done

2024-02-14 21:38 UTC, Winechicken commented on src/components/homePage/header/MainPageHeader.vue
> +			& button {
done

2024-02-14 21:40 UTC, Winechicken commented on src/components/homePage/section/CardBlock.vue
> +		<slot></slot>
done

2024-02-14 21:43 UTC, Winechicken commented on src/components/homePage/section/CreateForm.vue
> +				<ControlButton>
Thanks

2024-02-14 21:44 UTC, Winechicken commented on src/components/homePage/section/RecentForm.vue
> +// let changeImage = document.querySelector('#changeImage')
removed

2024-02-14 21:48 UTC, Winechicken commented on src/components/homePage/section/RecentForm.vue
> +						id="changeImage"
this id will be used later when we'll be implementing view changing by button click

2024-02-15 07:12 UTC, SavaCool122 commented on src/components/homePage/section/RecentForm.vue
> +						id="changeImage"
please fix

2024-02-15 15:12 UTC, Winechicken commented on src/components/homePage/section/RecentForm.vue
> +						id="changeImage"
done

2024-02-17 09:47 UTC, SavaCool122 approved these changes

2024-02-17 09:48 UTC, merged